name: gym_system
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.3
  # toastification: ^3.0.3
  # fluttertoast: ^8.2.4
  flash: ^3.1.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  lottie:
  croppy:
  bloc: ^9.1.0
  crypto: ^3.0.7
  path: ^1.9.1
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  get_it: ^9.0.5
  excel: ^4.0.6
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  hydrated_bloc: ^10.1.1
  cached_network_image: ^3.4.1
  flutter_gen_runner:
  build_runner:
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter_gen:
  output: lib/gen
  line_length: 50

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/loading/
    - assets/fonts/
    - assets/lang/


  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
    - family: CairoBold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: CairoRegular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
