name: Build All Platforms App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Packages
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release --bundle-msvc-redist

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: build/windows/x64/runner/Release/

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Packages
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-App
          path: build/app/outputs/flutter-apk/app-release.apk

  build-android-aab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Packages
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Android AAB
        uses: actions/upload-artifact@v4
        with:
          name: Android-AppBundle
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Packages
        run: flutter pub get

      - name: Build iOS Release
        run: flutter build ipa --release --no-codesign

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/ios/ipa/*.ipa

# name: Build Windows & Android App

# on:
#   push:
#     branches: [ "main" ]   # أي Push على main يشغل الـ workflow
#   workflow_dispatch:        # تشغيل يدوي لو حبيت

# jobs:
#   build-windows:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout Project
#         uses: actions/checkout@v4

#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - name: Enable Windows Desktop
#         run: flutter config --enable-windows-desktop

#       - name: Install Packages
#         run: flutter pub get

#       - name: Build Windows Release
#         run: flutter build windows --release

#       - name: Upload Windows EXE
#         uses: actions/upload-artifact@v4
#         with:
#           name: Windows-App
#           path: build/windows/x64/runner/Release/

#   build-android:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Project
#         uses: actions/checkout@v4

#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - name: Install Packages
#         run: flutter pub get

#       - name: Build Android APK
#         run: flutter build apk --release

#       - name: Upload Android APK
#         uses: actions/upload-artifact@v4
#         with:
#           name: Android-App
#           path: build/app/outputs/flutter-apk/app-release.apk

#   build-android-aab:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Project
#         uses: actions/checkout@v4

#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - name: Install Packages
#         run: flutter pub get

#       - name: Build Android App Bundle
#         run: flutter build appbundle --release

#       - name: Upload Android AAB
#         uses: actions/upload-artifact@v4
#         with:
#           name: Android-AppBundle
#           path: build/app/outputs/bundle/release/app-release.aab
